# Generated by Django 5.2.5 on 2025-08-11 03:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=128)),
                ('team_a', models.CharField(max_length=128)),
                ('team_b', models.CharField(max_length=128)),
                ('sport', models.CharField(max_length=64)),
                ('odds', models.FloatField(blank=True, null=True)),
                ('stake', models.FloatField()),
                ('status', models.CharField(default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
