# Generated by Django 5.2.5 on 2025-10-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_id', models.CharField(max_length=100)),
                ('team_a', models.CharField(max_length=120)),
                ('team_b', models.CharField(max_length=120)),
                ('sport', models.CharField(max_length=60)),
                ('odds', models.FloatField(blank=True, null=True)),
                ('stake', models.FloatField()),
                ('placement_fee', models.FloatField(default=0)),
                ('total_charged', models.FloatField(default=0)),
                ('vip_xp', models.IntegerField(default=1)),
                ('vip_multiplier', models.FloatField(default=1.0)),
                ('win_fee_rate', models.FloatField(default=0.05)),
                ('status', models.CharField(default='pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
